SELECT [Id]
      ,[ColDate]
      ,[ColTime]
      ,[ColDateTime]
      ,[ColChar]
      ,[ColVarchar]
      ,[ColIntRadio]
      ,[ColBitCheck]
      ,[ColIntTree]
      ,[ColFile]
      ,[ColFileName]
      ,[ColImage]
  FROM [dbo].[Template]
 Where [Id] = @Id